name: torch_control
description: Torch/flashlight control Flutter plugin
version: 0.1.0
homepage: https://github.com/jurem/flutter-torch_control

environment:
  sdk: ">=2.15.0-156.0.dev <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.topappfield.torch_control
        pluginClass: TorchControlPlugin
      ios:
        pluginClass: TorchControlPlugin
